jobs:
  build_js_backend:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      run: mvn --no-transfer-progress --batch-mode verify -P jstestsonly
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 20
  build_jvm:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      run: mvn --no-transfer-progress --batch-mode verify -P jvmtestsonly
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 20
  build_wasm_backend:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      run: mvn --no-transfer-progress --batch-mode verify -P wasmtestsonly
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 20
name: Pull Request
on:
  repository_dispatch:
    types: trigger-ga___pullrequest.yml
